### ISSUE TITLE
General problems

### ISSUE THREAD

**Issue by joao-v-maia** [LABMati/e-TIC#3]
Firefox overflow not working 
[https://stackoverflow.com/questions/28636832/firefox-overflow-y-not-working-with-nested-flexbox](url)

**Comment by felipekriffel** [comment]
### Consertado nos últimos commits. 

- **Motivo:** Por alguma razão(não descoberta), `overflow-x: hidden` no body não escondia as imagens do Carousel no firefox;
- **Solução:** Tirar o `overflow-x` do body e colocar `overflow: hidden` na section onde estava inserido o Carousel
