### ISSUE TITLE
Ajustes na página dos apoiadores

### ISSUE THREAD

**Issue by alaamaral** [LABMati/e-TIC#7]
Ajustes: 
- Alterar o texto "O evento será aberto..." para "O evento **é** aberto...";
- Tirar os telefones, deixar apenas o texto: "Nos comunique caso haja interesse em apoiar ou dúvidas."
- Alterar a ordem dos campos do formulário deixando assim: Nome, Assunto, E-mail, Telefone e Mensagem;
- Deixar a fonte do campo Mensagem igual as demais;
- Limpar os campos do formulário após o popup de confirmação do envio da mensagem.

**Comment by joao-v-maia** [comment]
Resolvido
